### ISSUE TITLE
BM DHO 

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dao-contracts#100]
**Summary:**
As a DHO admin I want to be able to create a new DHO with specific specifications that allows me to govern my organisation in a decentralised way. 

**Description:**

**Acceptance Criteria:** 
Steps to create a DHO

- [ ] 1. Create a unique URL / Subdomain (to be decided) 
- [x] 2. Create a config file (JSON)

  - DHO Name
  - DHO Purpose / Description
  - _Native token contract_ **SYMBOL** (default HYPHA)
  - _Voice token contract_ **SYMBOL** (default HVOICE)
  - (**NOT MVP**) Voice token decay config (optional)
  - _Peg token contract_ **SYMBOL** (default HUSD)
  - Reward token to Peg token ratio i.e. 1 HYPHA = 8 HUSD
  - Period duration
  - Voting duration
  - Onboarder account

- [x] 3. Import the config file (using a daoctl create command or JS EOSJS) @gerardo @max

> - [x] (Create a new DHO on the BM contract on the TestNet)
> - [x] (Get the new contract details for indexing @gerardo -> @sebastianmontero )

- [ ] 4. Create a new typed query endpoint for the testnet that indexes only the new BM DHO contract (@sebastianmontero )
- [ ] 5. Need the HASH for each of the DHOs (created into the test database) (?)
- [ ] 6. Setup the UI to show the 2 DHOs https://github.com/hypha-dao/dho-web-client/issues/325 (@luke)
- [ ] 7. Test creating a sample contribution on DHO1 and check if it not displayed on DHO2 @julio / @leonie / @nik

**Design**
https://xd.adobe.com/view/fc152647-45de-4a88-818a-0b4ff7f74ff5-a946/

**Comment by juliolrmonteiro** [comment]
Any updates on this? @leonieherma1 @Gerard097 @lukegravitt @n13
