### ISSUE TITLE
Reserach: Incremental automated backup system for the GraphDB (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dao-contracts#110]
**Summary:**
As a DHO user I would like to have a more stable DHO that doesn't lose any of my data automatically.

**Acceptance Criteria**
- [ ] Automate current backup system
- [ ] Research pricing of Pro Version of Dfuse for incremental and binary backups.
- [ ] Check possibility to restore backups from multiple instances (multiple clouds)

**Comment by sebastianmontero** [comment]
https://dgraph.io/docs/enterprise-features/binary-backups/

![image](https://user-images.githubusercontent.com/13155714/143171265-7bd8a887-dad1-4f9c-8379-457dc12e8bd2.png)
![image](https://user-images.githubusercontent.com/13155714/143171332-098f0592-a44d-4de3-b141-52ef4ddd6f98.png)
![image](https://user-images.githubusercontent.com/13155714/143171382-0596c02d-ad29-4754-86ff-30ce271960b9.png)
