### ISSUE TITLE
Commenting on Proposal Detail Page (Backend)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dao-contracts#125]
Summary:
As a DHO user I would like to be able to leave and reply to comments on a proposal detail page in order to get clarity on new proposals. 

Description:

Please add a "comment" widget below the description of new proposals on the proposal detail page. 

Acceptance Criteria:

- [ ] Every user should be able to leave a comment
- [ ] It should be possible to reply to comments (allow as many levels of comments as the user wants or max of 3?)
- [ ] User should be able to reply with an emoticon. Standard emoticons available?
- [ ] The total comment number should be visible on the preview card and proposal detail view
- [ ] Notifications for when someone leaves a comment (later)

Ressources:

Attachement:

https://xd.adobe.com/view/500c58dc-9103-41f4-a82a-bb390323fbd8-055f/screen/c20e1ce9-f9cf-4900-b68a-9bf9f9828c3e

**Comment by josejulio** [comment]
Do we want to keep the commens open and/or available when a proposal is published?

i.e. If a proposal is published should the comments be:
 - Stay open, anyone can still add more comments
 - Stay read-only, no one can add more comments but we can still see old comments.
 - Clean all comments

**Comment by leonieherma1** [comment]
I think commenting should always be possible. Is there anything that would speak against having the feature alway available? Could be handy for the members to discuss ongoing assignments especially before an extension

**Comment by leonieherma1** [comment]
We should also show the overall number of comments

**Comment by leonieherma1** [comment]
@josejulio @Gerard097 @arsenijesavic do you know if this can be closed?
