### ISSUE TITLE
New Document Type: Quest Start

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dao-contracts#138]
**Summary:**
As a DHO user I would like to be able to propose a quest proposal (Quest 0 / Quest Start) in order to get confirmation about starting a certain project.

**Description:**
This document type should only be used for quest starts. It is almost a clone of the contribution payout but the compensation should be disabled. So when the proposal gets voted in the compensation is not being paid. Later the member can propose the quest completion and will get paid the compensation that was agreed in the quest start document.

**Acceptance Criteria:**
Create New Document Type with the following attributes / fields:

- [ ]  Title
- [ ]  Description
- [ ]  Attachement
- [ ] Circle?
- [ ] Compensation Fields
- [ ]  Checkbox to "disable direct payout"

**Designs:**
https://xd.adobe.com/view/4d7b1ccc-0982-47ab-a2ce-99d07b70e0dd-1828/screen/456f5ed5-f6d0-46a2-ac10-e486a0c00df3

**Comment by josejulio** [comment]
`quest completion` is other proposal? IIUC one creates the `quest completion` off an approved `quest start`.
And once that one is approved the compensation is paid.

**Comment by leonieherma1** [comment]
> `quest completion` is other proposal? IIUC one creates the `quest completion` off an approved `quest start`.
> And once that one is approved the compensation is paid.

yes exactly. so it is just a button in the frontend that says "quest completed" and then creates a new document with an exact copy of the content of the quest start document. you can change the values, etc... and then "propose" it and when approved it gets paid out.
