### ISSUE TITLE
Research Task: Store images & frontend configurations in backend

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dao-contracts#157]
**Summary:** 
Where can we store uploaded logos, images & frontend configurations in the backend?

Fields that need to be stored @lukegravitt:

- [ ] logos
- [ ] background image
- [ ] 

Options:

- [ ] Amazon buckets
- [ ] profile service
- [ ] own ipfs node and pin it
- [ ] should be stored somewhere but governed on chain (Max)

**Comment by sebastianmontero** [comment]
**Existing Profile Service**

- Images could be stored in the profile of the user creating(or an account specific to the DAO) the DAO, enabling them to have control over the images thanks to the authentication already in place
- As the profile service is associated to an account the profile could be one related specifically to the dao and not a specific user
- The existing profile service stores the images in an amazon bucket
- No need to make any changes to the backend service
- Would only need to develop front end flow, which most probably would be part of the DAO creation wizard

**Use an existing IPFS service(Axel, Infura, Piñata)**

- No need to setup or maintain anything
- Providers are experts and dedicated to providing the infrastructure
- The Infura free tier could be enough for our needs at the moment

Example of costs:
Infura:
![image](https://user-images.githubusercontent.com/13155714/140758107-5c7ea2fa-598d-4ae4-b2b0-2543a0218e8c.png)

Pinata
![image](https://user-images.githubusercontent.com/13155714/140758266-7356e9fe-bee8-4689-a13c-2b430d795b85.png)


**Setup our own IPFS node**

- Setup and maintain the infrastructure
- Bear the costs of the infrastructure
- If we want to restrict access to who can pin on our server, we would need to develop an authentication layer, which is not provided by ipfs. Basically we would need to replicate one of the paid services.
- Could use a cloud provider or bare metal infrastructure


NOTE: For all alternatives I think that the location of the images and other DAO related configuration should be stored in a document on chain
