### ISSUE TITLE
set up IPFS for image storage (M)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dao-contracts#160]
**Summary:**
As a DHO Developer I want to store images (logos, banners, background images) on IPFS.

**Acceptance Criteria:**

- [x] Create IPFS credentials for DHO (@sebastianmontero)
- [x] Create upload input component (for images)
- [x] Create method to get real files (images) using the ipfs Id

https://github.com/hypha-dao/dao-contracts/issues/157

**Comment by jmgayosso** [comment]
HI @leonieherma1, I told with Luke and we think this issue should be closed, the core and base input are done, So the missing point (Include in DHO creation) should be done when we started to work in the creation DHO in other new issue, make sense for you?
