### ISSUE TITLE
The HVOICE Reset (S)

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dao-contracts#167]
## Spec

Every member of the DAO with voice 1 gets voice 1
Every member of the DAO with voice > 1 gets voice 5000

## Execution

- [x]  Create new branch PR for new voice contract code only changes
- [x] Add unit tests
- [x]  Deploy new voice contract
- [x] Create msig transaction that resets everyone's voice - iterating over all holders

**Comment by n13** [comment]
Execution

- [ ]  Create new branch PR for new voice contract code only changes
- [ ] Add a unit test in the system? It's tested but only on my branch with JS
- [ ]  Deploy new voice contract
- [ ] Create msig transaction that resets everyone's voice - iterating over all holders

**Comment by n13** [comment]
This is done.
