### ISSUE TITLE
Hypha Collective Liquidity Vesting Contract

### ISSUE THREAD

**Issue by n13** [hypha-dao/dao-contracts#173]
(formerly collective sales contract, but it's not a sales contract, it's a vesting contract)

## Spec

Vesting contract where balances can be sent on behalf of a user

Each lock has a default expiry of 3 years

Then there's a function to unlock a certain % for each user all at the same time

So for example, if 10% are unlocked - by calling the unlock(float percent) action - then each lock gets 10% unlocked

We could either keep a balance of liquid / locked on each lock, and have a claim() function where the liquid percentage can be claimed. 

Or we could automatically send out the % of tokens to their owners directly. 

Whichever way seems more natural.

**Comment by IanMendozaJaimes** [comment]
Hello @n13, I have some questions:
- I saw the collective sales contract, should we add the new contract to that repo?
- I assume this needs to use the document graph, right?
- How are the `balances` been transferred to the contract? using a token contract? does the contract need to support several token contracts?
- After those 3 years, the balance owner can claim the lock?, what will happen if we keep adding balance to the lock? or once a lock is created we can't add more balance to that lock?
- Does the contract need to support multiple locks per account?

Regarded to the `claim` action, I think it is easier if the users call that action by themselves

**Comment by IanMendozaJaimes** [comment]
Hello @n13, this could be the graph for this contract, what do you think?

![collective-liquidity-vesting-contract drawio](https://user-images.githubusercontent.com/9122978/145129189-0e6928a6-4803-41e1-bdf4-af1698b5f2b5.png)

**Comment by n13** [comment]
> Hello @n13, I have some questions:
> 
> * I saw the collective sales contract, should we add the new contract to that repo?

Yes can do that

> * I assume this needs to use the document graph, right?

Not really - any way it's best

My concern with document graph is that complexity might make it difficult to keep it free of holes?

> * How are the `balances` going to be transferred to the contract? with a transfer action using a token contract? does the contract need to support several token contracts?

Initially only Hypha token but would be cool so support more tokens. Just not sure we need that now so if it adds complexity we can leave it out.

> * After those 3 years, the balance owner can claim the lock?, what will happen if we keep adding balance to the lock? or once a lock is created we can't add more balance to that lock?

I was thinking it works the same way as the escrow contract we already have (in Seeds). 

It supports individual locks that expire individually, so more and more locks can be added per users, with different expiry dates. 

The difference is our locks can also be partially released before that time. 

So the question is is adding that functionality to the existing escrow contract more work or less work than doing the document graph above.

The diagram you created looks very good - makes a lot of sense as data architecture is concerned. 

> * Does the contract need to support multiple locks per account?
> 

Yes, see above


> Regarded to the `claim` action, I think it is easier if the users call that action by themselves

Ok that's fine. We can always write a claim crawler too if we need to.
