### ISSUE TITLE
Propose new period structure 

### ISSUE THREAD

**Issue by 3yekn** [hypha-dao/dao-contracts#22]
Extend periods out 1 year or so, and leave code in place so that it is easy to do again next year.  It should read from the cycle.seeds contract, but also add the extra labels for readable_start_time, readable_start_date, etc.  

Take a look at the 'UpdatePeriods' function in Go, although this is not organized very well at all: https://github.com/hypha-dao/dao-contracts/blob/efafded662ff9500067a0cf411681930bf584558/dao-go/setup.go#L134

**Comment by dappdever** [comment]
I updated periods to go out to the end of 2021. I will update them again soon, but I don't want to go out too far.

**Comment by leonieherma1** [comment]
Luke plans to propose new period structure
