### ISSUE TITLE
KPIs show 0

### ISSUE THREAD

**Issue by leonieherma1** [hypha-dao/dao-contracts#253]
**Summary**
As a new DAO user I would like to see the number 0 in the KPIs and not empty (looks broken)

https://dho.hypha.earth/samaratrust/configuration

<img width="271" alt="image" src="https://user-images.githubusercontent.com/75991832/166808448-ea092698-f72d-4850-815d-a3e29418c94b.png">

**Comment by DaniPoot** [comment]
This error has been solved in the dev branch
