### ISSUE TITLE
Voice.Hypha Deployment

### ISSUE THREAD

**Issue by dappdever** [hypha-dao/dao-contracts#36]
Native Ballots / New HVOICE Token
- [x] Step 1: deploy contract to voice.hypha @josejulio 
- [x] Step 1.a: create the HVOICE token itself (issuer: dao.hypha, decay time: 1 week, decay %: 1%) @josejulio 
- [x] Step 1.b: sync the balances - voice.hypha contract  @josejulio 
    - parameters (dao-contract, trailservice)
- [x] Step 2: update settings - add HVOICE_TOKEN_CONTRACT  - @dappdever 
- [x] Step 3: uncomment out HVOICE issuance from HVOICE-payer and member.enroll methods - @dappdever 
- [x] Step 4: update voice.hypha permissions  - @josejulio (@dappdever will provide the command)
- [x] Step 5: write spec for UI to pull token balance from new location  
    -- cleos get table voice.hypha hyphanewyork accounts

**Comment by josejulio** [comment]
The steps on the lists are done. Missing details are to:
- Use voice.hypha to determine the voting power & quorum (all in proposal class)
