### ISSUE TITLE
Native Ballots

### ISSUE THREAD

**Issue by dappdever** [hypha-dao/dao-contracts#4]
Currently, the DHO uses telos decide (previously known as "trailservice") for ballots and voting. We want to replace telos decide with ballots and vote tallies that we track ourselves within the document graph.

grepping the code for "decide" is a good way to get an idea of what will need to change.  

There are 3 impacted actions:
1.  Propose - instead of calling "newballot", we will save the data into a document (https://github.com/hypha-dao/dao-contracts/blob/develop/src/proposals/proposal.cpp#L149)
2.  Vote - instead of callint "vote" on the telos decide contract, there will be a new "vote" action on the dao contract
3.  Close Proposal - a proposal stays votable for 1 week (based on the setting ```voting_period_sec```).  Then it is closed, at which point the votes are tallied, it is determined if it passed, and appropriate behavior takes place.   (https://github.com/hypha-dao/dao-contracts/blob/develop/src/proposals/proposal.cpp#L99)

I developed a first attempt at this on the old repo.  You can find it under the ```native-ballots``` branch of the old repo here: NOTE this code won't compile as is with the new libraries, but it provides a sense for what I was doing. 

https://github.com/hypha-dao/eosio-contracts/blob/native-ballots/src/proposal.cpp#L239-L371

For now, we only need to support pass/fail proposals.  However, in the future, we will want to expand on this quite a bit, including functionality like elections, multi-voting, voting with scores, etc.

**Comment by dappdever** [comment]
Is this a duplicate?  @josejulio

**Comment by josejulio** [comment]
I think this is already done - If something more specific is needed a separate issue could be created.
